### PR TITLE
changed line break to lf

### PR DESCRIPTION
**Pull request by matsubo**
- bugfix.
- please accept asap.

### CODE REVIEW

**Comment by ka2n** [comment]
@matsubo How about change remote to [rayburgemeestre/phpfolding.vim](https://github.com/rayburgemeestre/phpfolding.vim)?

**Comment by ghost** [comment]
Which is origin?
rayburgemeestre/phpfolding.vim ,which you suggested, is forked from vim-scripts/phpfolding.vim

**Comment by ka2n** [comment]
Hi @yuki-matsukura  san,
According to `CONTRIBUTE` section of README.

```
I do not own vim-scripts, so please fork mine instead:
    https://github.com/rayburgemeestre/phpfolding.vim
It's then easier for me to accept pull requests and upload new version(s) here,
```

 rayburgemeestre/phpfolding.vim is origin, I think :smiley:

**Comment by matsubo** [comment]
Allright thanks.
I'll send PR to the rayburgemeestre/phpfolding.vim.

**Pull request closed without merging**
